import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Activity, Zap, Heart, Target, Star, ArrowRight, CheckCircle, Users, Trophy, TrendingUp } from 'lucide-react'

const stats = [
    { icon: <Users size={24} className="stat-icon" />, value: '10K+', label: 'Active Users', color: '#a855f7' },
    { icon: <Zap size={24} />, value: '50K+', label: 'Workouts Completed', color: '#06b6d4' },
    { icon: <Heart size={24} />, value: '₹2L+', label: 'Raised for Charity', color: '#ec4899' },
    { icon: <Trophy size={24} />, value: '95%', label: 'Success Rate', color: '#f59e0b' },
]

const features = [
    { icon: '🤖', title: 'AI-Powered Plans', desc: 'Get personalized workout and nutrition plans generated by advanced AI', color: '#a855f7' },
    { icon: '📅', title: 'Smart Scheduling', desc: 'Automatic Google Calendar integration for seamless plan management', color: '#06b6d4' },
    { icon: '📊', title: 'Goal Tracking', desc: 'Track your progress with detailed analytics and achievement badges', color: '#10b981' },
    { icon: '❤️', title: 'Charity Impact', desc: 'Turn your fitness journey into charitable donations automatically', color: '#ec4899' },
]

const reviews = [
    { name: 'Priya Sharma', role: 'Software Engineer', rating: 5, text: '"ArogyaMitra transformed my fitness journey! The AI plans are spot-on and the charity aspect keeps me motivated."' },
    { name: 'Rahul Kumar', role: 'Student', rating: 5, text: '"Love how it syncs with my Google Calendar. Never miss a workout now! Highly recommended."' },
    { name: 'Anita Patel', role: 'Doctor', rating: 5, text: '"The nutrition plans are scientifically sound and easy to follow. Best health app I\'ve used!"' },
]

export default function LandingPage() {
    const navigate = useNavigate()
    return (
        <div className="page" style={{ background: 'var(--bg-primary)' }}>
            {/* Navbar */}
            <nav className="navbar">
                <a className="navbar-logo" href="/">
                    <span>💪</span> ArogyaMitra
                </a>
                <div className="navbar-links">
                    <a href="#features" className="nav-link">Features</a>
                    <a href="#reviews" className="nav-link">Reviews</a>
                </div>
                <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                    <Link to="/login" className="btn-secondary" style={{ padding: '8px 18px', fontSize: 14 }}>Login</Link>
                    <button className="btn-primary" style={{ padding: '8px 20px', fontSize: 14 }} onClick={() => navigate('/register')}>Get Started</button>
                </div>
            </nav>

            {/* Hero */}
            <section style={{ position: 'relative', overflow: 'hidden', minHeight: '88vh', display: 'flex', alignItems: 'center' }}>
                <div className="orb orb-purple" style={{ top: '-100px', left: '-100px' }} />
                <div className="orb orb-pink" style={{ bottom: '0', right: '-50px' }} />
                <div className="container" style={{ width: '100%', textAlign: 'center', position: 'relative', zIndex: 1, paddingTop: 60 }}>
                    <div className="float" style={{ fontSize: 56, marginBottom: 24 }}>✨</div>
                    <h1 style={{ fontSize: 'clamp(40px, 6vw, 80px)', fontWeight: 900, lineHeight: 1.15, marginBottom: 24 }}>
                        Your AI Fitness<br />
                        <span className="gradient-text">Companion</span>
                    </h1>
                    <p style={{ fontSize: 18, color: 'var(--text-secondary)', maxWidth: 560, margin: '0 auto 40px', lineHeight: 1.7 }}>
                        Transform your health journey with personalized AI-powered workout plans, nutrition guidance, and automatic charity donations. Join thousands who've already started their transformation!
                    </p>
                    <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
                        <button className="btn-primary" style={{ fontSize: 16, padding: '14px 36px', display: 'flex', alignItems: 'center', gap: 8 }} onClick={() => navigate('/register')}>
                            Start Free Journey <ArrowRight size={18} />
                        </button>
                        <button className="btn-secondary" style={{ fontSize: 16, padding: '14px 36px' }} onClick={() => navigate('/login')}>
                            Already a Member? →
                        </button>
                    </div>
                    <div style={{ display: 'flex', gap: 24, justifyContent: 'center', marginTop: 40, flexWrap: 'wrap' }}>
                        {['✓ Free to start', '✓ No credit card required', '✓ Cancel anytime'].map(t => (
                            <span key={t} style={{ fontSize: 13, color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 6 }}>{t}</span>
                        ))}
                    </div>
                </div>
            </section>

            {/* Stats */}
            <section style={{ background: 'var(--bg-secondary)', padding: '48px 0', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)' }}>
                <div className="container">
                    <div className="grid-4">
                        {stats.map((s, i) => (
                            <div key={i} className="stat-card" style={{ alignItems: 'center', textAlign: 'center' }}>
                                <div style={{ color: s.color, marginBottom: 8 }}>{s.icon}</div>
                                <div className="stat-value gradient-text">{s.value}</div>
                                <div className="stat-label">{s.label}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Features */}
            <section id="features" className="section">
                <div className="container">
                    <div style={{ textAlign: 'center', marginBottom: 56 }}>
                        <h2 style={{ fontSize: 40, fontWeight: 800, marginBottom: 16 }}>Why Choose <span className="gradient-text">ArogyaMitra?</span></h2>
                        <p style={{ color: 'var(--text-secondary)', fontSize: 17 }}>Experience the future of fitness with our AI-powered platform that adapts to your lifestyle</p>
                    </div>
                    <div className="grid-4">
                        {features.map((f, i) => (
                            <div key={i} className="card" style={{ textAlign: 'center' }}>
                                <div style={{ fontSize: 40, marginBottom: 16, background: `${f.color}22`, width: 68, height: 68, borderRadius: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>{f.icon}</div>
                                <h3 style={{ fontSize: 17, fontWeight: 700, marginBottom: 8, color: f.color }}>{f.title}</h3>
                                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.65 }}>{f.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Reviews */}
            <section id="reviews" style={{ background: 'var(--bg-secondary)', padding: '80px 0', borderTop: '1px solid var(--border)' }}>
                <div className="container">
                    <div style={{ textAlign: 'center', marginBottom: 56 }}>
                        <h2 style={{ fontSize: 40, fontWeight: 800 }}>What Our <span className="gradient-text">Users Say</span></h2>
                        <p style={{ color: 'var(--text-secondary)', marginTop: 12 }}>Join thousands of satisfied users who transformed their lives</p>
                    </div>
                    <div className="grid-3">
                        {reviews.map((r, i) => (
                            <div key={i} className="card card-glow">
                                <div style={{ color: '#f59e0b', marginBottom: 12, fontSize: 18 }}>{'★'.repeat(r.rating)}</div>
                                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 16 }}>{r.text}</p>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                    <div style={{ width: 36, height: 36, borderRadius: '50%', background: 'var(--gradient-main)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, fontSize: 14 }}>{r.name[0]}</div>
                                    <div>
                                        <div style={{ fontWeight: 600, fontSize: 14 }}>{r.name}</div>
                                        <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{r.role}</div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="section" style={{ textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
                <div className="orb orb-purple" style={{ top: '-100px', right: '-100px', opacity: 0.5 }} />
                <div className="container" style={{ position: 'relative', zIndex: 1 }}>
                    <h2 style={{ fontSize: 44, fontWeight: 900, marginBottom: 16 }}>Ready to Transform <span className="gradient-text">Your Life?</span></h2>
                    <p style={{ color: 'var(--text-secondary)', marginBottom: 40, fontSize: 17 }}>Join ArogyaMitra today and start your personalized fitness journey with AI guidance</p>
                    <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
                        <button className="btn-primary" style={{ fontSize: 16, padding: '14px 36px' }} onClick={() => navigate('/register')}>Start Your Journey 🚀</button>
                        <button className="btn-secondary" style={{ fontSize: 16, padding: '14px 36px' }} onClick={() => navigate('/login')}>Already a Member? →</button>
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer style={{ borderTop: '1px solid var(--border)', padding: '24px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>
                © 2024 ArogyaMitra – AROMI AI Agent. Built with ❤️ for health & wellness.
            </footer>
        </div>
    )
}
